baseURL = "https://echorand.me"
languageCode = "en-us"
title = "Exploring Software"
theme = "hugo-classic"

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

[[menu.main]]
    name = "Books"
    url = "/books"
    weight = 1

[[menu.main]]
    name = "Articles"
    url = "/articles"
    weight = 1

[[menu.main]]
    name = "Talks"
    url = "/talks"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"
