baseURL = "https://echorand.me"
languageCode = "en-us"
title = "Exploring Software"
theme = "hello-friend-ng"
googleAnalytics = "UA-108901610-1"
enableGitInfo = true
lastmod = ["lastmod", ":fileModTime", ":default"]

[params]

  homeSubtitle = "echo $RANDOM"

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

[[menu.main]]
    name = "Books"
    url = "/books"
    weight = 1

[[menu.main]]
    name = "Articles"
    url = "/articles"
    weight = 1

[[menu.main]]
    name = "Talks"
    url = "/talks"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"
