baseURL = "https://echorand.me"
languageCode = "en-us"
title = "Exploring Software"
theme = "etch"
googleAnalytics = "UA-108901610-1"
enableGitInfo = true
lastmod = ["lastmod", ":fileModTime", ":default"]

[params]
  description = "echo $RANDOM. Exploring Software and writing about it."
  mainSection = "posts"
  showAllPostsOnHomePage = true
  postsOnHomePage = 20 
  tagsOverview = true
  showProjectsList = false
  show_updated = true
  rss = true
  dark = "auto"

[[params.social]]
  name = "github"
  link = "https://github.com/amitsaha"

[[params.social]]
  name = "email"
  link = "amitsaha.in@gmail.com" # no need for "mailto:" at the start

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/echorand/"

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

[[menu.main]]
    name = "Writings and Trainings"
    url = "/writings-trainings"
    weight = 1

[[menu.main]]
    name = "Talks"
    url = "/talks"
    weight = 1

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 2

[[menu.main]]
    name = "Subscribe (RSS)"
    url = "/index.xml" 
    
