name = "Hugo - Classic"
license = "MIT"
licenselink = "https://github.com/goodroot/hugo-classic/blob/master/LICENSE.md"
description = "A minimal blog theme, for those who love text. Based off the eXtremely minimal theme by Yihui Xui."
homepage = "https://goodroot.ca"
tags = ["minimal", "blog", "personal", "simple", "clean", "starter", "minimalist"]
features = ["blog"]
min_version = "0.18"

[author]
  name = "Kellen Evan Person"
  homepage = "https://goodroot.ca"

[original]
  author = "Yihui Xui"
  homepage = "https://xmin.yihui.name/"
  repo = "https://github.com/yihui/hugo-xmin"
