name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build docker image
      run: docker build -t amitsaha/echorandme-publisher .
    - name: Build site
      run: |
        docker run -v `pwd`:/site -t amitsaha/echorandme-publisher
